### ISSUE TITLE
BehaviourSpace and Goo

### ISSUE THREAD

**Issue by cazgp** [NetLogo/Goo-Extension#2]
java.lang.ClassCastException: org.nlogo.headless.HeadlessWorkspace cannot be cast to org.nlogo.window.GUIWorkspace
at org.nlogo.extensions.goo.Helpers$class.workspace(GooExtension.scala:46)
 at org.nlogo.extensions.goo.SetChooserItems.workspace(GooExtension.scala:146)
 at org.nlogo.extensions.goo.Helpers$class.invokeAndWait(GooExtension.scala:62)
 at org.nlogo.extensions.goo.SetChooserItems.invokeAndWait(GooExtension.scala:146)
 at org.nlogo.extensions.goo.SetChooserItems.perform(GooExtension.scala:152)
 at org.nlogo.prim._extern.perform(_extern.java:54)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
 at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at scala.util.control.Exception$Catch.apply(Exception.scala:88)
 at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:75)

**Comment by cazgp** [comment]
Fixed with a wrapper:

```
if behaviorspace-run-number = 0 [
    goo:set-chooser-items "chooser" list-name
]
```

**Comment by SethTisue** [comment]
nice workaround

**Comment by cazgp** [comment]
Thanks :) I don't have any time to teach myself Scala to create a PR for this. Thanks for the work, this has been really useful. LMK if I can do a bit of testing for you.

**Comment by SethTisue** [comment]
closing open issues as the project seems abandoned
